include: package:netglade_analysis/lints_package.yaml

dart_code_metrics:
  extends:
    - package:netglade_analysis/dcm.yaml
  pubspec-rules:
    prefer-publish-to-none: false
  rules:
    prefer-boolean-prefixes: false # TODO
    prefer-named-parameters: false # TODO
