targets:
  $default:
    builders:
      :auto_mappr:
        enabled: true
        generate_for:
          exclude:
            - test/integration/error_fixture/**
        options:
          ignoreNullableSourceField: true

builders:
  auto_mappr:
    import: "package:auto_mappr/auto_mappr.dart"
    builder_factories: ["autoMapprBuilder"]
    build_extensions: { ".dart": [".auto_mappr.dart"] }
    auto_apply: dependents
    build_to: source
    required_inputs: [".freezed.dart", ".drift.dart"]
